package com.azavea.gtfs

/** Represents a scheduled transit system.
    Generated by the TransitSystemFactory
    that generates the schedules between a start
    time and an end time. */
trait TransitSystem {
  val routes: Seq[Route]
  def routes(routeType: RouteType): Seq[Route]
}
